default-test-config: &default-test-config
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        key: dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install
    - save_cache:
        paths:
          - node_modules
        key: dependencies-{{ checksum "yarn.lock" }}
    - run: yarn test

version: 2
jobs:
  test-node-8:
    <<: *default-test-config
    docker:
      - image: circleci/node:8.9.4
  test-node-9:
    <<: *default-test-config
    docker:
      - image: circleci/node:9.5.0
  release:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: npm run semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test-node-8
      - test-node-9
      - release:
          requires:
            - test-node-8
            - test-node-9